### ISSUE TITLE
Unavailable Tables

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#125]
For tables that are unavailable, such as 5-5, there is still a shell table when I access the table directly from the URL, not the provided table.  Should this be changed to "report not available" at some point?

![image](https://cloud.githubusercontent.com/assets/9752096/6927257/227bf788-d7ba-11e4-8ef4-cf09042a2dbd.png)

**Comment by awolfe76** [comment]
Yeah. So we should even show that option in the table list right?

**Comment by lesgou** [comment]
Hmm, so there are two situations in which a table is not available:
1) The MSA/MD/Bank did not have that particular activity, so no table was generated.
2) Table 5.5 and Table 10 don't exist at all, and we don't know why yet.

So, when I change the URL to 5-5 or 10, should a 404 appear instead of a shell?

**Comment by awolfe76** [comment]
For 1), I don't think we should even list those tables as options in the select box, but we haven't built that yet. We don't have a list of available tables for each. This is similar to the `msa-mds.json` file that we have for states. For each MSA/MD we should also create a `reports.json` file that lists the available reports and use that to populate the select box.

For 2), the solution for 1) helps, but in the case that someone just changes the URL to a report that doesn't exist we should show a 404. It's just a broken URL. Someone could just type `alabama` wrong and the same thing would happen.

For the example you gave, 5-5 currently **does** have a `.json` file there. It's just all 0's. We should have an issue, maybe just use this one, to make a change so that 5-5 doesn't even get created and to create the `reports.json` for each MSA/MD.

How do we know that 5-5 doesn't (or shouldn't) exist? Other than the ffiec site?

**Comment by lesgou** [comment]
Yup, I agree, we aren't listing those tables as options in the select box.  But would the URL also be broken if the report doesn't exist?

We are checking on whether 5-5 and 10 should exist.....but, it may take some time.

**Comment by awolfe76** [comment]
Oh, ok. So 5-5 and 10 are never there. And yeah, if the report doesn't exist it's a 404. But ideally, someone wouldn't get a 404 by using the UI, only by trying to change the URL manually.

If I'm remembering right, it's also possible that 3-1 doesn't exist for an MSA/MD. Right?
Or is it that all the other reports will be there, except for 5-5 and 10 at the moment? And maybe a few others?

**Comment by Kibrael** [comment]
For reference, I changed the code that was producing 5-5 and it will not be produced in the future. Unless we decide we actually want it that is.

**Comment by awolfe76** [comment]
@lesgou @Kibrael 
Added 2 issues to handle this, #158 and #159.
