### ISSUE TITLE
Number of MSA's in data vs in a search

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-viz-prototype#30]
I ran a query on the HMDA data and found that there are 393 Metropolitan Statistical Areas (MSA) listed.
Query: `SELECT COUNT(*) FROM (SELECT DISTINCT msaofproperty FROM hmda_lar_public_final_2012) AS temp;`

Doing a quick Google there are 381 listed, plus 7 for Puerto Rico, for 388 total. Why the difference?

The answer is the in the data we have a set of Metropolitan Divisions (MD) counted as MSAs.

@lesgou - if you want to add more detail please do.

**Comment by lesgou** [comment]
Reporters are currently asked to file at the lowest level, which is the MD. Since there are not that many MDs, most LARS reported are then at the MSA level.  And, instead of having the data two separate columns, one for MSA and one for MDs, they are combined into one.  The Google search likely only produced a list of only MSAs, while the HMDA data includes MDs and MSAs.

Thanks @debseidner for the clarification!

**Comment by debseidner** [comment]
Something else to remember is that you are only seeing the MSAs/MDs that financial institutions have originated a loan in over a particular year. It is possible that not every MSA or MD is covered in a year's HMDA filing.

**Comment by debseidner** [comment]
Copied in the MSA/MD data I pulled from Census into the A&D folder as @Kibrael requested - https://drive.google.com/drive/#folders/0B667BGHwjTznYmd5dndmSGdhdHM/0B667BGHwjTznMW94cDVBSENvRFE/0B4c9-dK8OVSQUHpQOG1KN213b2s

**Comment by awolfe76** [comment]
Thanks @debseidner!
