### ISSUE TITLE
report 3-1: verify that race setting

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-viz-prototype#39]
verify that co-applicant minority races are used for a loan if the applicant race is not reported

**Comment by Kibrael** [comment]
@lesgou this is one of those weird edge cases that I don't think will ever happen, do you think Jaydee might know how this is done in practice?

**Comment by awolfe76** [comment]
Just going through this milestone - any updates on this one?

**Comment by lesgou** [comment]
We can close this issue.  If the applicant race/ethnicity is N/A, but co-applicant race/ethnicity is not N/A, we will use the co-applicant's race/ethnicity.  This is after our conversation with Regs.  The reason is that the goal is to capture info relating minority applications, so this doing this will capture that information.
