### ISSUE TITLE
Update directory names

### ISSUE THREAD

**Issue by lesgou** [cfpb/hmda-viz-prototype#84]
The directory names need to be hyphenated and match what is in the msa-md.json files

http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/california/los-angeles-long-beach-santa-ana/
- [ ] all msa names hyphenated (no spaces or underscores, and only one hyphen)
- [ ] all state names hyphenated

**Comment by awolfe76** [comment]
Yeah, for all directories the states and msas should be hyphenated. Need to watch for spaces and possibly underscores too. There are also a few cases where there are double hyphens:
`SACRAMENTO--ARDEN-ARCADE--ROSEVILLE`

That's in http://awolfe76.github.io/hmda-viz-prototype/aggregate/2012/california/msa-mds.json

**Comment by Kibrael** [comment]
This one is entered that way in the cbsa database. Should I change it?

**Comment by awolfe76** [comment]
That's odd. Downside there is that is if it's in the db like that (and in the json) the directory needs to match it. But having the -- in the url probably isn't a good idea.
So you can either change the db or when you process it convert it to a single -. I would do the change when you are processing so that the source data remains the same, so someone else wouldn't have to change that to match ours.

**Comment by Kibrael** [comment]
I asked Mike about whether the -- was correct. He said it was not. I changed the db for the Sacrament-Arden-Arcade-Rosewood.

I wasn't able to figure a quick python fix. If we need to fix it in python after, we can reopen this issue.

**Comment by awolfe76** [comment]
:+1:
